server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/electronic_album
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver

  jackson:
    default-property-inclusion: non_null

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # photo_id -> photoId
